services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "80:80"
    environment:
      - REACT_APP_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env  

  api-server:
    image: api-server
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    env_file:
      - .env 
