version: '3'
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "80:80"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

  api-server:
    image: api-server
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}

